remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: Ayano Okoso
description: >
  Researcher @ Toyota Central R&D Labs., Inc.<br>
  Ph.D. student @ The University of Tokyo
show_downloads: false

# Add custom CSS
include:
  - assets/css/style.css
